import Link from 'next/link'
import Image from 'next/image'
import Head from 'next/head'
import Script from 'next/script'
import Layout from '../../components/layout'
export default function FirstPost() {
    return (
        <Layout home={false}>
            <Head>
                <title>First Post</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/robot.svg" />
            </Head>
            {/* Third party script */}
            {/* load this particular script lazily during browser idle time */}
            {/* <Script
                src="https://connect.facebook.net/en_US/sdk.js"
                strategy="lazyOnload"
                onLoad={() =>
                console.log(`script loaded correctly, window.FB has been populated`)
                }
            /> */}

            <h1>First Post</h1>
            <h2>
                {/* Link is used to use javascript navigate between pages, instead of browser reload */}
                <Link href="/">← Back to home</Link>
            </h2>
            <Image src="/images/avatar.png"
                height={144}
                width={144}
                alt="Zhijie Xia" />
        </Layout>
    )
}